name: MSBuild

on:
  pull_request:
    paths-ignore:
      - '**/README.md'

env:
  SOLUTION_FILE_PATH: CP_Main_10.sln

jobs:
  build:
    runs-on: windows-latest
    strategy:
      fail-fast: false
      matrix:
        platform: [x64, ARM64]
    env:
      VCPKG_ROOT: C:\vcpkg
    steps:
      - uses: actions/checkout@v4

      - name: Add MSBuild to PATH
        uses: microsoft/setup-msbuild@v2

      - name: Build ${{ matrix.platform }}
        run: msbuild ${{ env.SOLUTION_FILE_PATH }} /p:Configuration=Release /p:Platform=${{ matrix.platform }} /m
